---
###########################
###########################
## Markdown Linter rules ##
###########################
###########################

# Linter rules doc:
# - https://github.com/DavidAnson/markdownlint
#
# Note:
# To comment out a single error:
#   <!-- markdownlint-disable -->
#   any violations you want
#   <!-- markdownlint-restore -->
#

default: true

###############
# Rules by id #
###############
MD004: false # Unordered list style
MD007:
  indent: 2 # Unordered list indentation
MD013:
  line_length: 500 # Line length 80 is far to short
MD024: false #/no-duplicate-heading/no-duplicate-header
MD026:
  punctuation: '.,;:!。，；:' # List of not allowed
MD029: false # Ordered list item prefix
MD036: false # Emphasis used instead of a heading
MD049: false # emphasis-style Emphasis style should be consistent

#################
# Rules by tags #
#################
blank_lines: false # Error on blank lines
