
import * as d from '../components';

export const DIRECTIVES = [
  d.DbAccordion,
  d.DbBrand,
  d.DbBreadcrumb,
  d.DbButton,
  d.DbCard,
  d.DbCards,
  d.DbCheckbox,
  d.DbChip,
  d.DbDropdown,
  d.DbFooter,
  d.DbHeader,
  d.DbHeadline,
  d.DbIcon,
  d.DbImage,
  d.DbInput,
  d.DbLanguageSwitcher,
  d.DbLink,
  d.DbLinklist,
  d.DbLogo,
  d.DbMainnavigation,
  d.DbMeta,
  d.DbMetanavigation,
  d.DbNotification,
  d.DbNotifications,
  d.DbOverflowMenu,
  d.DbPage,
  d.DbPagination,
  d.DbProgress,
  d.DbRadio,
  d.DbSelect,
  d.DbSidenavi,
  d.DbTab,
  d.DbTabBar,
  d.DbTable,
  d.DbTag,
  d.DbTextarea,
  d.DbToggle,
  d.GithubVersionSwitcher
];
