---
name: 'NPM Cache Action'
description: 'Initialize NPM Cache'
inputs:
  nodeModulesPath:
    description: 'Path for node_modules'
    required: false
    default: '**/node_modules'
  packageLockPath:
    description: 'Path for package-lock.json'
    required: false
    default: '**/package-lock.json'
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Setup node equally to our local development version
      # pick the Node version to use and install it
      # https://github.com/actions/setup-node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Display node and npm version
      shell: bash
      run: |
        node --version
        npm --version

    - uses: actions/cache@v4
      id: 'cache'
      with:
        path: ${{ inputs.nodeModulesPath }}
        key: ${{ runner.os }}-node-${{ hashFiles(inputs.packageLockPath) }}
        restore-keys: |
          ${{ runner.os }}-node-
