---
name: 'Cancel Workflow'
description: 'Cancel this workflow on failure'
runs:
  using: 'composite'
  steps:
    - run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/db-ui/elements/actions/runs/${{ github.run_id }}/cancel
      shell: bash
