name: 'Bundle GitHub Page'
description: 'This action bundles the current gh-page branch with the out folder'
inputs:
  latest:
    description: 'This has to be true if you want to overwrite latest.'
    required: false
    default: 'false'
  tag:
    description: 'This has to be a tag like v1.0.0 if you want to push a tag to the /version folder'
    required: false
runs:
  using: 'composite'
  steps:
    - name: ↔ Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: ➕ Create temp or public dir
      run: |
        echo "Create dir for branch: ${{ steps.extract_branch.outputs.branch }}"
        if [ ${{ inputs.latest }} == "true" ];
        then
          mkdir temp
          echo "Created 'temp' dir"
        else
          mkdir public
          echo "Created 'public' dir"
        fi
      shell: bash
    - name: 📥 Get gh-pages tar
      run: wget -q https://github.com/db-ui/elements/tarball/gh-pages
      shell: bash
    - name: 📦 Unpack Tar
      run: |
        if [ ${{ inputs.latest }} == "true" ];
        then
          tar -zxf gh-pages -C temp --strip-components 1
        else
          tar -zxf gh-pages -C public --strip-components 1
        fi
      shell: bash
    - name: 📁 Move ./out folder to public
      run: |
        if [ ${{ inputs.latest }} == "true" ];
        then
          mv ./out ./public
          if [ -d ./temp/review ]; then
            mv ./temp/review ./public
          fi
        elif [ ! -d ${{ inputs.tag }} ];
        then
          if [ ! -d ./public/version ]; then
            mkdir ./public/version
          fi
          mv ./out ./public/version/${{ inputs.tag }}
        else
          if [ ! -d ./public/review ]; then
            mkdir ./public/review
          fi
          if [ -d ./public/review/${{ steps.extract_branch.outputs.branch }} ]; then
            rm -rf  ./public/review/${{ steps.extract_branch.outputs.branch }}
          fi
          mv ./out ./public/review/${{ steps.extract_branch.outputs.branch }}
        fi
      shell: bash
