#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --yes pretty-quick --staged
node ./scripts/cypress-component-check.js
node ./scripts/angular-module-component-check.js
npm run lint:eslint
npm run lint:stylelint
npm run lint:markdownlint
npm run lint:jscpd
npx validate-branch-name

