#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --yes pretty-quick --staged
npx concurrently "node ./scripts/check-commit-mail.js" "node ./scripts/cypress/component-check.js" "node ./scripts/angular-module-component-check.js" "npm run lint:stylelint" "npm run lint:markdownlint" "npx validate-branch-name"







