---
name: Install Cypress

on:
  workflow_call:

jobs:
  install-cypress:
    name: Install Cypress
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v7

      - name: 💻 Install dependencies
        uses: cypress-io/github-action@v7
        with:
          working-directory: e2e
          runTests: false

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
