---
name: 🔬 Run unit/snapshot tests

on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v7

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: 🔬 Run unit/snapshot tests
        run: npm test

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
