---
name: 🔬 Validate repo

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v7

      - name: 🔄 Init Cache
        uses: ./.github/actions/npm-cache

      - name: 🔬 Validate repo
        run: |
          node ./scripts/cypress/component-check.js
          node ./scripts/angular-module-component-check.js
          npm run lint:eslint
          npm run lint:stylelint
          npm run lint:markdownlint

      - name: 💀 Killing me softly
        uses: ./.github/actions/cancel-workflow
        if: failure()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
