name: Print Cypress Summary

on:
  workflow_call:

jobs:
  print-cypress-summary:
    name: Print Cypress Summary
    runs-on: ubuntu-latest
    steps:
      - name: ⬇ Checkout repo
        uses: actions/checkout@v3

      - name: ⬇ Download summary for areas
        uses: ./.github/actions/download-tar-artifact
        with:
          name: areas-summary
          path: areas-summary

      - name: ⬇ Download summary for components
        uses: ./.github/actions/download-tar-artifact
        with:
          name: components-summary
          path: components-summary

      - name: ⬇ Download summary for elements
        uses: ./.github/actions/download-tar-artifact
        with:
          name: elements-summary
          path: elements-summary

      - name: ⬇ Download summary for showcases
        uses: ./.github/actions/download-tar-artifact
        with:
          name: showcases-summary
          path: showcases-summary

      - name: 🖨️ Print cypress summary
        run: |
          echo "<h2>Cypress Results</h2>" > $GITHUB_STEP_SUMMARY

          CONTAINERS=('areas' 'components' 'elements' 'showcases')
          for container in "${CONTAINERS[@]}"
          do
            fileName=${container}-summary
            sed "s/Cypress Results/$fileName/g" ${fileName}
            sed "s/h2/h3/g" ${fileName}
            cat "${fileName}" >> $GITHUB_STEP_SUMMARY
          done

          echo $GITHUB_STEP_SUMMARY
