---
name: On-Pull-Request opened

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: write

jobs:
  add-url-comment:
    if: github.event.pull_request.head.repo.owner.login == 'db-ui'
    uses: ./.github/workflows/99-add-url-comment.yml
